### ISSUE TITLE
D3D: hardcoded Vertex Element SemanticName 

### ISSUE THREAD

**Issue by thatcosmonaut** [thatcosmonaut/SDL#120]
Oh what a surprise, HLSL semantics are causing issues again. 

Some shader code emitters like Naga output a LOC semantic instead of TEXCOORD.

For example, this code:
```
struct Vertex {
    @location(0) position: vec2f,
    @location(1) color: vec3f,
};
```

generates this HLSL output:

```
struct Vertex {
    float2 position : LOC0;
    float3 color : LOC1;
};
```

Our D3D renderers expect a hardcoded TEXCOORD semantic for input layouts. We could include a semantic name field in the vertex attribute struct, but that concept doesn't make sense for anything except D3D. It's also not clear if the client will even be aware of the semantic choice if they are using a generator or cross-compiler.

**Comment by thatcosmonaut** [comment]
Apparently post-SM4 D3D vertex semantics are just arbitrary strings.

Upon consideration I think that hardcoding this is fine and we should just arbitrarily decide on a semantic name to be expected for all vertex inputs. It doesn't necessarily have to be TEXCOORD but that's the default which is emitted by SPIRV-Cross so it's probably a reasonable default.

**Comment by flibitijibibo** [comment]
Aside from the HLSL compilation part, we can make the semantic name an SDL_Properties value for those who don't have control over what name the compiler uses for locations.

**Comment by flibitijibibo** [comment]
Going to add this as part of #74

**Comment by flibitijibibo** [comment]
https://github.com/thatcosmonaut/SDL/commit/2e75cb3a20aff6eab7eccda49a4c76645ce1a52b
