### ISSUE TITLE
Change primitiveCount to vertexCount

### ISSUE THREAD

**Issue by flibitijibibo** [thatcosmonaut/SDL#135]
This is an old carryover from FNA3D/D3D9, and people porting from OpenGL will rightfully hate this, so let's take this math out.

**Comment by bartwe** [comment]
Review needed around SDL_GpuDrawIndexedPrimitives and struct SDL_GpuIndirectDrawCommand explicitly

**Comment by thatcosmonaut** [comment]
Indirect draw structs already used vertex count so they don't need to change.

**Comment by thatcosmonaut** [comment]
Addressed by https://github.com/thatcosmonaut/SDL/pull/136
