### ISSUE TITLE
Add Bind[Vertex/Fragment]SamplerSlices

### ISSUE THREAD

**Issue by thatcosmonaut** [thatcosmonaut/SDL#141]
We're already keeping track of 2D subresources for relevant texture types, so we could add a path to bind slices for samplers instead of the entire texture. This would be useful for clients and simplify the Blit source path a lot. 

There might be a better name for this function.

**Comment by flibitijibibo** [comment]
Is this affected by #179?

**Comment by thatcosmonaut** [comment]
Yeah we can close this now.
