### ISSUE TITLE
Support for 32bit stencil is not available on all backends, suggest switching to 8 bit

### ISSUE THREAD

**Issue by bartwe** [thatcosmonaut/SDL#146]
DX11 and DX12 only support 8 bit.
Alternatively D3D12_BeginRenderPass does not allow argument validation.

**Comment by thatcosmonaut** [comment]
I really don't know that this is necessary, all the stencil inputs for backends are unsigned 32-bit and get truncated to 8-bit by the driver.

**Comment by thatcosmonaut** [comment]
I stand corrected, D3D11 and D3D12 take a Uint8 while Vulkan and Metal take a Uint32. I really don't feel strongly about this except for wanting to know why Vulkan/Metal went with a 4-byte field.

**Comment by bartwe** [comment]
talked it through with a few experts, they weren't aware of any currently available targets that were not 8bit.

**Comment by TheSpydog** [comment]
Resolved by #165
