### ISSUE TITLE
D3D12: Add object lookup for indirect command signatures

### ISSUE THREAD

**Issue by thatcosmonaut** [thatcosmonaut/SDL#153]
We need a blit pipeline object per texture format on D3D12, and we need a command signature for each stride value.

**Comment by flibitijibibo** [comment]
Fixed via #162

**Comment by thatcosmonaut** [comment]
Still need to do stride support for indirect calls.

**Comment by flibitijibibo** [comment]
Fixed (for real this time!) by #220
