### ISSUE TITLE
The Monolithic SDL_Properties Thread

### ISSUE THREAD

**Issue by flibitijibibo** [thatcosmonaut/SDL#157]
Two possibilities to start:

> `SDL_GpuCreateShaderWithProperties()` for future expansion?

In agreement with this one because of how much APIs like to break shaders, but the next one...

> Does it make any sense to add SDL_PropertiesID props; to any of these structures for future expansion?

I may actually drag @icculus in for this one; one thing we discussed is that it's pretty much impossible to predict the future re: GPU APIs, but this one seems harmless enough to add as long as it doesn't get put _everywhere_ in the header?

**Comment by slouken** [comment]
Yeah, the balance we've tried to strike in the rest of the SDL API, is any complex object has an optional properties ID associated with it that the application can use for any reason, and then any API that has complex parameters has a simple version and a complex version with properties. The idea being that applications using the "Simple" part of "Simple DirectMedia Layer" don't ever see them, but people can jump out of the sandbox for more complex scenarios or platform-specific needs.

**Comment by flibitijibibo** [comment]
Turns out this was pretty easy since every resource has its own createinfo struct, so we just added a properties field to the ends of those. All "created" objects in GPU should now have extensibility via SDL_Properties!
