### ISSUE TITLE
The Monolithic Enum Hardening Thread

### ISSUE THREAD

**Issue by bartwe** [thatcosmonaut/SDL#158]
SDL_GPU_TEXTUREFORMAT_INVALID is defined as -1, which means that if someone forgets to initializes the arguments to a texture or swapchain they'll get a working system instead of an error as 0 is a valid enum entry.

**Comment by flibitijibibo** [comment]
Similarly, we need to have MAX values so that backends can have static assertions for their translation arrays. Making this consistent across all the enumerations should be done before we merge.

**Comment by bartwe** [comment]
using _COUNT not _MAX as it doesn't collide with an existing _MAX entry in SDL_GpuBlendOp

**Comment by bartwe** [comment]
Also added _MASKCHECK which tells which bits are allowed to be used in a bit flag enum

**Comment by bartwe** [comment]
Ready for review/merge

**Comment by flibitijibibo** [comment]
Upgrading this to Beta, since it's a task that risks changing ABI.

**Comment by thatcosmonaut** [comment]
I'm souring on this, both because I don't think 0 should be invalid and because I think including MAX in all our enums makes them too brittle and encourages clients to loop on them. There's very few examples of MAX values across public SDL enums. If we really want to validate enum values in functions we can always check internally what we know to be the largest enum value.

**Comment by flibitijibibo** [comment]
SDL does do static asserts for arrays based on enums, but only some enums actually have `SDL_NUM_##thing` at the end, so we'd have to come up with some other way to make sure the assertions are doing their job if stuff gets added (not likely for most of  them, but texture format in particular I could see getting additions over the next decade).

@slouken, any preferences for how enum/arraysize validation is set up?

**Comment by slouken** [comment]
I don't have a strong preference. Typically adding to the end of enums doesn't break application code that iterates until a previously known maximum, but you do have to be careful how you treat new enum values.

I think whatever works for you guys and ends up being the least brittle and accidentally broken by future us is fine.

**Comment by flibitijibibo** [comment]
#215 puts something together for TextureFormat which is the one we expect to get additions in the future. We _may_ need to do this for swapchain composition as well but it's not as urgent; once that PR is in this can be bumped to Ship.

**Comment by flibitijibibo** [comment]
This recently got worked on via https://github.com/libsdl-org/SDL/pull/10786 but I don't think we do any validation yet.

**Comment by thatcosmonaut** [comment]
There is validation on any enum that has an INVALID entry. I feel pretty good about where things are right now with respect to enums so I'm closing this.
