### ISSUE TITLE
On DX12/DX11 SDL_GpuSupportsSwapchainComposition returns true when HDR not supported

### ISSUE THREAD

**Issue by bartwe** [thatcosmonaut/SDL#167]
but SDL_GpuSetSwapchainParameters returns false for HDR when not supported

**Comment by bartwe** [comment]
Partially handled by ensuring the return value of SDL_GpuSetSwapchainParameters is not ignored. but this defo has some stink to it. Given that it has that return value, do we need SDL_GpuSupportsSwapchainComposition at all ?

**Comment by thatcosmonaut** [comment]
The client should not be passing in parameters that haven't been verified by checking SDL_GpuSupportsSwapchainComposition. The only reason SetSwapchainParameters has a return value is because recreating the swapchain can fail for reasons other than composition support.

**Comment by flibitijibibo** [comment]
That sounds like the OP issue - HDR is claimed to work but then doesn't, might be that texture format is checked but not colorspace yet?

**Comment by flibitijibibo** [comment]
Yeah this one's not too bad - just have to add one more check to this block https://github.com/thatcosmonaut/SDL/blob/gpu_next/src/gpu/d3d12/SDL_gpu_d3d12.c#L5536

**Comment by thatcosmonaut** [comment]
Yeah colorspace is not being checked. Should also make sure that the present mode is being checked beforehand in whichever example this is failing on because that can also cause SetSwapchainParameters to fail.

**Comment by bartwe** [comment]
Trouble is that check is on     IDXGISwapChain3_CheckColorSpaceSupport(
        swapchain3,
        windowData->swapchainColorSpace,
        &colorSpaceSupport);

    if (!(colorSpaceSupport & DXGI_SWAP_CHAIN_COLOR_SPACE_SUPPORT_FLAG_PRESENT)) {

which is after creating a swapchain.. so not sure you can check it that early ?

**Comment by bartwe** [comment]
Is it perhaps dependent on which monitor the output is sent to ? that'd be annoying

**Comment by thatcosmonaut** [comment]
What happens if we create a temporary swapchain in that function and release it? It's janky but we have to do something similar in Vulkan for capability queries.

**Comment by bartwe** [comment]
Could do, likely would want SDL_GpuPresentMode on the call to SDL_GpuSupportsSwapchainComposition  then too ?

**Comment by thatcosmonaut** [comment]
Checking the present mode is a separate function. DXGI presentation is a unique case anyway because we are guaranteed support based on feature level.

**Comment by flibitijibibo** [comment]
This affects D3D11 as well. Could potentially be an excuse to share DXGI logic in d3dcommon if they don't use it too differently.

**Comment by flibitijibibo** [comment]
Per #158 let's also validate the enum value, similar to TextureFormat.
