### ISSUE TITLE
DX12 requests that a texture optionally has a clear value associated 

### ISSUE THREAD

**Issue by bartwe** [thatcosmonaut/SDL#168]
D3D12 WARNING: ID3D12CommandList::ClearRenderTargetView: The clear values do not match those passed to resource creation. The clear operation is typically slower as a result; but will still clear to the desired value. [ EXECUTION WARNING #820: CLEARRENDERTARGETVIEW_MISMATCHINGCLEARVALUE]

Add a D3D12_CLEAR_VALUE argument to ID3D12Device_CreateCommittedResource it needs the textureformat, but the one of the rtv not the texture itself.

**Comment by flibitijibibo** [comment]
Probably something for #157

**Comment by thatcosmonaut** [comment]
This is one of those weird D3D12-isms that doesn't really make sense in any other backend. I agree that a property for it might make sense but nothing more.

**Comment by flibitijibibo** [comment]
https://github.com/thatcosmonaut/SDL/commit/5b93d39bd990a436c2804b7cb6947602bdeb1cdc
