### ISSUE TITLE
TriangleMSAA doesn't look the same between vulkan and dx11

### ISSUE THREAD

**Issue by bartwe** [thatcosmonaut/SDL#170]
vulkan: 
![image](https://github.com/user-attachments/assets/f655f52b-fa9c-48cf-b5d5-a576929c831c)
dx11:
![image](https://github.com/user-attachments/assets/e2775e51-c179-48b0-984e-ae374cb0c754)

pixels are sharper and color more vibrant on the 1x mode on dx11

**Comment by flibitijibibo** [comment]
Should be fixed at the same time as #84

**Comment by flibitijibibo** [comment]
Fixed via #162
