### ISSUE TITLE
SDL_gpu.h missing includes ?

### ISSUE THREAD

**Issue by mpalomas** [thatcosmonaut/SDL#189]
Hi,

So I was trying to parse SDL_gpu.h, for my own reasons, using some wrappers around libclang.

Anyway, it turns out SDL_gpu.h does use a couple of SDL types:

> SDL_FColor
> SDL_PropertiesID
> SDL_Rect
> SDL_Window

But they are neither included nor forward declared.

At the top of the file, you only include
> #include <SDL3/SDL_stdinc.h>

If you look at SDL_render.h, it does include all the necessary .h it is using, so it is "standalone".

I'm not sure whether this is intended, maybe I'm missing something.

**Comment by flibitijibibo** [comment]
I don't _think_ it is but I also don't know if we're supposed to insist on parsing SDL.h only. For now you can patch this up locally to make the parser work and send it our way, we can always change it if upstream prefers it another way.

**Comment by flibitijibibo** [comment]
This got fixed upstream!
