### ISSUE TITLE
MapTransferBuffer should return the mapped pointer

### ISSUE THREAD

**Issue by TheSpydog** [thatcosmonaut/SDL#195]
Instead of having it as an out parameter. The Vulkan/D3D Map functions return an error code, but since our API doesn't use error codes, we might as well just make it return the pointer for convenience. A null pointer will indicate something went wrong.

**Comment by thatcosmonaut** [comment]
Marking this as Beta since it's definitely an ABI break.

**Comment by TheSpydog** [comment]
Resolved by #196
