### ISSUE TITLE
`frameCounter` Overflows `textureContainers` on Vulkan

### ISSUE THREAD

**Issue by steviegt6** [thatcosmonaut/SDL#208]
Looking at examples in [SDL_gpu_examples on `next`](https://github.com/TheSpydog/SDL_gpu_examples/tree/next) and discovered strange rendering in the `Clear3DSlice` example (the framerate of the GIF is low so it doesn't do the flashing justice):
![devenv_YccyzTVGOm](https://github.com/user-attachments/assets/cce49c8b-3585-4db8-adb2-e9eb0c4adecd)

Discovered it occurs when `frameCounter == 2` here:
```c
    *pWidth = swapchainData->textureContainers[swapchainData->frameCounter].header.info.width;
    *pHeight = swapchainData->textureContainers[swapchainData->frameCounter].header.info.height;
```

`textureContainers` only contains two elements so it reads out of bounds and returns invalid data, resulting in odd dimensions in this case.

Further digging found that this is because `minImageCount` is equal to 1, resulting in `imageCount` being set to 2 which is less than `MAX_FRAMES_IN_FLIGHT`:
```
    swapchainData->imageCount = swapchainSupportDetails.capabilities.minImageCount + 1;
```

As a quick test I tweaked handling of `frameCounter` to reset in accordance to `imageCount` if it is less than `MAX_FRAMES_IN_FLIGHT`:
```c
        presentData->windowData->swapchainData->frameCounter =
            (presentData->windowData->swapchainData->frameCounter + 1) % (presentData->windowData->swapchainData->imageCount < MAX_FRAMES_IN_FLIGHT ? presentData->windowData->swapchainData->imageCount : MAX_FRAMES_IN_FLIGHT);
```

This worked as expected but I don't know if it's necessarily the best approach or if `imageCount` should remain this low. All other examples have worked as expected thus far. It even fixed an issue I was having with ComputeUniforms that resulted in a crash (I hadn't gotten to debugging this yet but it turned out to be the same issue).

**Comment by thatcosmonaut** [comment]
I have no idea why I set imageCount to min + 1, we've probably just been getting lucky this whole time that the value is generally 2. We should just set it to MAX_FRAMES_IN_FLIGHT.

**Comment by thatcosmonaut** [comment]
Patch is in `gpu_next` branch, if you could confirm the fix on your machine that would be great.

**Comment by steviegt6** [comment]
Can confirm it's working as intended now:
![image](https://github.com/user-attachments/assets/5a10c9a6-d5a1-4416-ac63-6691f6858225)
