### ISSUE TITLE
Thoughts on GetBestSampleCount

### ISSUE THREAD

**Issue by TheSpydog** [thatcosmonaut/SDL#218]
Sample counts are currently the one case where we fall back gracefully if the client passes in an unsupported value to TextureCreateInfo. If you request an 8x MSAA texture but that sample count is not supported, no problem! We'll internally call `GetBestSampleCount` to fall back to 4, then 2, then 1.

I'm not completely sure if it makes sense to have this fallback logic. It's convenient, but in general our API tends more towards explicitness. You're expected to check which depth formats are supported, for instance, so it seems like maybe the same should apply here as well?

However, if we do want to keep the fallback logic, then is there ever a reason to call `GetBestSampleCount` on the client side? The one use case I can think of is for determining which sample counts are supported, like for an options screen or something. In which case it'd probably be better to have a `SDL_GpuSupportsSampleCount` that just gives you a bool, rather than giving you the "best" option which you then have to compare against your original query.

Additionally, right now the fallback logic is implemented separately for each driver. Their CreateTexture functions are calling `GetBestSampleCount` to get the "actual" sample count that will be used to create the texture. If we want this behavior, we might as well cut the redundancy and perform this check at the `SDL_GpuCreateTexture` level. (I can do this as part of the D3D12 MSAA work.)

**Comment by flibitijibibo** [comment]
I'm in favor of removing the fallback, since a silent behavior change would probably be really awful to debug if you have techniques that require AA (RL2's old alpha to coverage bug comes to mind).

**Comment by thatcosmonaut** [comment]
Let's remove it. I think the most common case for MSAA involves exposing it to the user as a setting anyway, so the client can just query which counts are supported for their render target formats.

**Comment by thatcosmonaut** [comment]
Resolved by #225
