### ISSUE TITLE
Remove UINT texture formats

### ISSUE THREAD

**Issue by TheSpydog** [thatcosmonaut/SDL#219]
They present portability problems since D3D11/12 can't sample from them, and their use cases are very niche. We could add these back in the future if someone has a real-world need for them.

**Comment by sulix** [comment]
I'd prefer to keep the UINT formats if we can: I'm using ``SDL_GPU_TEXTUREFORMAT_R8_UINT`` quite a bit for emulating paletted surfaces, and while I can't use them with samplers any more, it works fine as a shader read resource instead.

That being said, I (a) haven't tested this with anything other than the Vulkan backend yet, and (b) can relatively easily work around it if they're missing. But _logically_ I'm dealing with a texture with UINT properties, and either emulating that by un-normalising a UNORM version, or using something else (putting the data in a buffer) isn't quite as clean.

**Comment by flibitijibibo** [comment]
That's pretty similar to the other use case we had - alright, we'll try to make sure to document this as one of those formats that's useful outside of just sampling, probably as part of #217.
