### ISSUE TITLE
Unable to render anything on D3D11

### ISSUE THREAD

**Issue by RandyGaul** [thatcosmonaut/SDL#237]
After the latest SDL_Gpu update https://github.com/libsdl-org/SDL/commit/95bf26e3a0c979accc63a8811b151ce3f74e6ce6 I've been unable to get anything render under D3D11. I only get one warning:

```
D3D11 WARNING: ID3D11DeviceContext::DrawInstanced: Vertex Buffer at the input vertex slot 0 is not big enough for what the Draw*() call expects to traverse. This is OK, as reading off the end of the Buffer is defined to return 0. However the developer probably did not intend to make use of this behavior.  [ EXECUTION WARNING #356: DEVICE_DRAW_VERTEX_BUFFER_TOO_SMALL]
```

After some debugging I'm left scratching my head on why this warning is emit at all. I'm just rendering a single triangle, 36 bytes in total, 12 per vertex, and confirmed passing in well formed parameters when creating the `SDL_GpuBuffer` and calling `SDL_GpuDrawPrimitives`. The only change on my end has been to add in `1, 0` for instance count and offset.

Vulkan/D3D12 seem totally fine. I am using `SDL_GpuBlit` to get an offscreen buffer onto the screen and suspect that may be relevant. Here are renderdoc captures for the 3 backends (attached below), from this [sample program here](https://github.com/RandyGaul/cute_framework/blob/gpu/samples/hello_triangle.c):

[rdc.zip](https://github.com/user-attachments/files/16735247/rdc.zip)

**Comment by thatcosmonaut** [comment]
Probably a regression from the instanced draw update...

**Comment by thatcosmonaut** [comment]
Fixed by https://github.com/thatcosmonaut/SDL/commit/e40efb4b5c256dbd09287df9aea820f99a67d6f3
