### ISSUE TITLE
Texture Format Swizzling

### ISSUE THREAD

**Issue by TheSpydog** [thatcosmonaut/SDL#56]
Some of the texture formats we expose are only natively supported by Vulkan, but they have swizzled variants that are supported by all the other APIs. I think we should expose the most common formats and have fallback swizzling as needed for the backends that lack native support.

* **R5G6B5**: Replace with B5G6R5 for D3D and Metal. Vulkan has 69.62% coverage for B5G6R5 as a native sampler format.
* **A1R5G5B5**: Replace with B5G5R5A1 for D3D and Metal. Vulkan has 83.39% coverage for BGG5R5A1 as a native sampler format.
* **B4G4R4A4**: Supported by Vulkan and D3D, but not by Metal. Since Metal's the odd one out, we can swizzle its A4B4G4R4 format.
* **A2R10G10B10**: Replace with R10G10B10A2 for D3D and Metal. Vulkan has _no_ native support for that swizzling.
* **A2B10G10R10**: Replace with B10G10R10A2 for D3D and Metal. Vulkan has _no_ native support for that swizzling.

**Comment by flibitijibibo** [comment]
Out of all the APIs Vulkan has the best support for built-in swizzling, we should use the formats that other APIs natively support and swizzle as needed for Vulkan (or use a native format if an extension like EXT_4444_formats is available). FNA has been able to handle this, so we can take notes from our own Vulkan renderer if needed.
