### ISSUE TITLE
Verify SDL3 namespacing

### ISSUE THREAD

**Issue by flibitijibibo** [thatcosmonaut/SDL#66]
Should be easy enough, but will take a nonzero amount of time so here's a ticket!

**Comment by slouken** [comment]
Question... should the API be SDL_GPU*? instead of mix-casing an acronym?

**Comment by flibitijibibo** [comment]
I like GPU over Gpu but I recall there being a reason we did it like this... @thatcosmonaut do you remember anything here? It's pretty easy to change this so I could go either way.

**Comment by flibitijibibo** [comment]
Actually I remember now: Ryan's API chose Gpu so we just went with his style - @icculus, any opinion on this?

**Comment by thatcosmonaut** [comment]
Fine with me either way.

**Comment by icculus** [comment]
So here's where I ruin everyone's day by like 10%, I'm sorry in advance.

I personally like "Gpu" better because I think "SDL_GPUWhatever" looks bad, but I also chose this before we went wild renaming all the SDL3 APIs to be consistent.

Since we renamed everything else, _none_ of these should be "SDL_GpuSetWidget" anymore; it would be more like "SDL_SetGpuWidget" now... `SDL_`+verb+noun. It's going to be a simple search/replace or perl script, but it's a little more of a pain in the butt than just changing the capitalization.

Imho, I _still_ think the camel casing looks better in the newer form, but there are lots of things in SDL that don't do this (SDL_LoadWAV, SDL_HasNEON, SDL_GetJoystickGUID, etc), so we should probably go with "GPU" here, too.

@slouken, agree?

**Comment by slouken** [comment]
I don't feel strongly about GPU vs Gpu. I suggest that the first part of the renaming, to change to verb+noun be done, and people look and see how they like it, and whether we search and replace Gpu with GPU.

FYI, build-scripts/rename_symbols.py is a handy tool if you want to automate some of this, and includes a `--substring` command line option.

**Comment by slouken** [comment]
Also, having GPU in the name isn't necessarily a requirement, e.g. `SDL_DestroyTexture()`. If it refers unambiguously to something in the new API, it can stand alone. The final API should be reviewed for sanity and consistency though.

**Comment by icculus** [comment]
Okay, let's do the nasty part first then, and we'll revisit afterwards.

(There is a risk of people getting confused, though, when they wonder why they can't use SDL_CreateTexture with the GPU API, so as things get renamed, use your best judgment and we'll make a pass over it at that point.)

**Comment by thatcosmonaut** [comment]
Given how much overlap there is with SDL_render terminology, it's probably less confusing to just put the GPU qualifier on everything - if it has GPU in it you'll know for sure that it's part of the GPU API.

**Comment by slouken** [comment]
> Given how much overlap there is with SDL_render terminology, it's probably less confusing to just put the GPU qualifier on everything - if it has GPU in it you'll know for sure that it's part of the GPU API.

Sounds good.

**Comment by icculus** [comment]
>  it's probably less confusing to just put the GPU qualifier on everything - if it has GPU in it you'll know for sure that it's part of the GPU API.

Agreed.

**Comment by flibitijibibo** [comment]
We've effectively hit Beta minus this task and a few minor bugfixy things, so I'll push the weekly update today and then on Monday I'll run the C++ comment script at https://github.com/libsdl-org/SDL/commit/6501e90018ab1d58047e5b4382c6bc6d04051191 as well as a custom script for both SDL and other repos to automatically rename all functions to the new scheme, and that _should_ take care of everything!

**Comment by slouken** [comment]
FYI, I'm in the process of removing the status code from the SDL API, switching a ton of functions from int to SDL_bool return values. I think you're already here, but the rest of SDL is being updated to match.

**Comment by slouken** [comment]
I changed SDL API functions to return SDL_bool instead of int, so they should be consistent with the GPU API. Go ahead and make sure you're not using the old approach when you're doing the naming revamp?

**Comment by flibitijibibo** [comment]
Confirmed that we use void, SDL_bool, or a Gpu pointer for return types, so we should be all set there!

**Comment by slouken** [comment]
> Confirmed that we use void, SDL_bool, or a Gpu pointer for return types, so we should be all set there!

Great!

**Comment by flibitijibibo** [comment]
Resolved in gpu_next, which will be pushed to gpu in just a moment...
