### ISSUE TITLE
Vulkan uniform buffer leak

### ISSUE THREAD

**Issue by TheSpydog** [thatcosmonaut/SDL#83]
If you do the following:
```
BeginPass();
BindGraphicsPipeline(somePipelineWithUniforms); 
// Other stuff, but NO draws!
EndPass();
```
Then a ton of uniform buffers are reported as "not destroyed" by the validation layer when the GpuDevice is destroyed. Seems like drawing somehow allows them to be released properly.

In normal scenarios you'd never bind a pipeline without drawing something, but still, something to investigate.

**Comment by thatcosmonaut** [comment]
I think we just need to call TrackUniformBuffer at bind time instead of draw time.
