### ISSUE TITLE
Blit does not support source regions in D3D/Metal

### ISSUE THREAD

**Issue by TheSpydog** [thatcosmonaut/SDL#84]
In D3D11 and Metal, the whole source image is used instead of the region specified in the Blit command. We'll need to write in support for that in the BlitFrom* shaders.

(As a side note, it may be possible to combine the BlitFrom2D and BlitFrom2DCube shaders for D3D11 since apparently HLSL can treat Texture2Ds as Texture2DArrays with a length of 1.)

**Comment by flibitijibibo** [comment]
Pretty sure this affects D3D12 as well, so it's basically all non-Vulkan renderers... updated the title accordingly!

**Comment by thatcosmonaut** [comment]
After discussion we decided that Blit should have a lot more restrictions - namely, that you can only blit between two textures that are 2D and use the same color format. This will be useful for the most common use case, which is a final blit to the swapchain, and prevent everyone from having to write the same pipeline for this, but it prevents us from having to implement extremely complex Vulkan-conformant blits for every backend.

**Comment by flibitijibibo** [comment]
Fixed via #162
