### ISSUE TITLE
Vulkan: CreateDevice fails to create a dummy window on non-desktop platforms

### ISSUE THREAD

**Issue by TheSpydog** [thatcosmonaut/SDL#90]
The order of window / GPU device initialization can affect whether the device is successfully created.
```
// This is fine!
SDL_GpuCreateDevice();
SDL_CreateWindow();

// This will fail on certain platforms!
SDL_CreateWindow();
SDL_GpuCreateDevice();
```

The problem is that the device is attempting to create a dummy window it can use for querying surface support, but some platforms (e.g. Android, Switch) only allow for 1 window at a time.

**Comment by flibitijibibo** [comment]
https://github.com/thatcosmonaut/SDL/commit/7ff968fd82955f6737015888c5048a139625e18b
