### ISSUE TITLE
Finish texture format enum

### ISSUE THREAD

**Issue by flibitijibibo** [thatcosmonaut/SDL#98]
- [ ] ASTC
- [ ] S8, no depth
- [x] R11G11B10F
- [x] BC1_SRGB
- [x] BC5/6?
- [x] Signed integer formats?

Thanks to @slime73 for reminding us of these!

**Comment by Akaricchi** [comment]
* `SDL_GPU_TEXTUREFORMAT_R8G8` is missing even though `R8G8_SNORM` and `R8G8_UINT` exists; pretty sure that anything that supports those two will support the UNORM variant as well.
* `BC5` (2-component format) should definitely be added.

These are very useful for tangent-space normal maps where the Z component is implicit and is reconstructed in the shader.

* `BC4` (1-component format) can be useful for stuff like roughness and metallic maps, though one might be better off packing them into a single texture.
* Generally would be nice to have [all the targets supported by the Basis Universal transcoder](https://github.com/BinomialLLC/basis_universal/wiki/OpenGL-texture-format-enums-table), maybe except for obscure stuff like ATC and FXT1. ETC1 can probably be omitted too as it's a subset of ETC2. The `PVRTC` formats (especially `PVRTC1`) have some weird requirements and I'm not sure how relevant they are.
* `R16` and `R16_SNORM` for the sake of completeness; `R16_FLOAT` and `R16_UINT` exist so I'm assuming our backends support UNORM and SNORM variants for this as well, but I'm not sure.

**Comment by slime73** [comment]
I agree with most of those, PVRTC is deprecated in vulkan and metal (and ETC2 and ASTC replace it) so I don't think that one's needed though.

**Comment by flibitijibibo** [comment]
We've covered what we can cover, the only two we didn't do are ASTC and STENCIL8. Stencil8 is surprisingly unsupported across APIs and hardware; hypothetically we could fake it with a depth-stencil format but that's a lot of memory to waste behind everybody's back.

ASTC we should definitely support but that may need to be done by a mobile dev that can test it properly.
